#!/usr/bin/env python3
"""Generate build/<tool>/Dockerfile files from declarative recipes.

Recipes live in scripts/gen_recipes.py. Run from repo root:

    python3 scripts/gen_dockerfiles.py            # write all
    python3 scripts/gen_dockerfiles.py jq yq      # write a few

Conventions every generated Dockerfile follows:
  - stage `build` compiles at ARG VERSION, producing stripped+UPX-packed
    binaries under /out/x64/ and (when the tool ships ARM) /out/arm/
  - final stage is alpine with everything under /out (sh available so
    scripts/build.sh can smoke-test inside the container)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from gen_recipes import RECIPES  # noqa: E402

BASE_ALPINE = "alpine:3.20"
GO_IMAGE = "golang:1.25-alpine"
RUST_IMAGE = "rust:1-alpine"

# musl.cc is unreachable from some CI networks; mirror the exact tarball
# (sha256 3bd7bed4...) as a release asset on this repo.
ARM_TC_URL = ("https://github.com/mosajjal/binary-tools/releases/download/"
              "toolchain-v1/armtc.tgz")

HEADER = """\
# Generated by scripts/gen_dockerfiles.py -- edit recipes there, not here.
# Builds {name} {version_note}statically for x64{arm_note}.
# usage: docker build --build-arg VERSION={example_ver} -t bt/{name} {dir}
"""

FETCH_GH = """\\
RUN git clone --depth 1 --branch {prefix}{VERSION} https://github.com/{slug}.git /src
"""

FETCH_TARBALL = """\\
RUN mkdir -p /src && curl -fsSL --retry 3 --retry-delay 2 "{url}" | tar {tarflags} -C /src --strip-components=1
"""


_DECOMP = {".tar.xz": "unxz -c", ".tar.gz": "gunzip -c",
           ".tgz": "gunzip -c", ".tar.bz2": "bunzip2 -c", ".tar.lz": "lzip -dc"}


def _curl_untar(url):
    """Fetch a tarball and untar into /src; decodes by extension (busybox-safe)."""
    suffix = next((e for e in _DECOMP if e in url), ".tar.gz")
    return (f'RUN mkdir -p /src && curl -fsSL --retry 3 --retry-delay 2 "{url}" | {_DECOMP[suffix]} '
            "| tar x -C /src --strip-components=1")


def fetch_lines(r):
    if r.get("tarball"):
        url = r["tarball"].replace("{v}", "${VERSION}").replace("{vmajor}", "${VERSION%%.*}")
        return _curl_untar(url)
    if r.get("release_tarball"):
        t = r["release_tarball"].replace("{v}", "${VERSION}")
        ver = "${VERSION}"
        if r.get("tag_transform") == "dots_to_underscores":
            ver = '${VERSION//./_}'
        url = (f"https://github.com/{r['slug']}/releases/download/"
               f"{r.get('tag_prefix', '')}{ver}/{t}")
        return _curl_untar(url)
    repo = r.get("clone_url") or f"https://github.com/{r['slug']}.git"
    depth = "" if r.get("full_clone") else "--depth 1 "
    if r.get("branch"):
        return f"RUN git clone {depth}{repo} /src"
    prefix = r.get('tag_prefix', '')
    # Shallow clones only fetch the default branch. For tag/commit checkouts
    # we must fetch the tag explicitly first. Try several tag spellings that
    # cover historical mismatches (dnstt v1.20241021 vs v1.20241021.0, icmptunnel
    # v prefix, tor-0.4.8.0, etc.) and finally a plain commit hash checkout for
    # logtop-style pinned versions.
    return (
        f"RUN git clone {depth}{repo} /src && cd /src && "
        f"REF=\"{prefix}${{VERSION}}\" && "
        f"(git fetch --depth 1 origin tag $REF 2>/dev/null; git checkout $REF 2>/dev/null) || "
        f"(git fetch --depth 1 origin tag $REF.0 2>/dev/null; git checkout $REF.0 2>/dev/null) || "
        f"(git fetch --depth 1 origin tag v${{VERSION}} 2>/dev/null; git checkout v${{VERSION}} 2>/dev/null) || "
        f"(git fetch --depth 1 origin tag v${{VERSION}}.0 2>/dev/null; git checkout v${{VERSION}}.0 2>/dev/null) || "
        f"(git fetch --depth 1 origin tag ${{VERSION}} 2>/dev/null; git checkout ${{VERSION}} 2>/dev/null) || "
        f"(git fetch --unshallow 2>/dev/null || git fetch --depth 1000 origin 2>/dev/null; git checkout ${{VERSION}} 2>/dev/null) || true; cd /"
    )


def sh(lines):
    return "\n".join(lines)


def run_block(lines):
    """Render shell lines as one RUN step with && continuations."""
    body = "".join(f" && {l} \\\n" for l in lines[:-1]) + f" && {lines[-1]}\n"
    return "RUN set -ex \\\n" + body


def go_recipe(name, r):
    # cgo=True: tool needs a C dependency (e.g. mattn/go-sqlite3). Link the C
    # runtime statically via the external linker so the binary stays static.
    cgo = r.get("cgo", False)
    ldflags = "-s -w"
    if cgo:
        ldflags += " -linkmode external -extldflags=-static"
    if r.get("ldflags"):
        ldflags += " " + r["ldflags"]
    b = [
        f"FROM {GO_IMAGE} AS build",
        "ARG VERSION",
        f"ENV CGO_ENABLED={'1' if cgo else '0'} GOTOOLCHAIN=auto",
    ]
    if cgo:
        # gcc + static musl for the native (x64) cgo link
        b.append("RUN apk add --no-cache build-base")
    if r.get("pkgs"):
        b.append(f"RUN apk add --no-cache {' '.join(r['pkgs'])}")
    b += [
        "RUN apk add --no-cache git ca-certificates upx",
        fetch_lines(r),
    ]
    for d, u in r.get("extra_clones", []):
        if r.get("branch"):
            b.append(f"RUN git clone --depth 1 {u} /src/{d}")
        else:
            b.append(f"RUN git clone --depth 1 --branch {r.get('extra_tag_prefix', '')}${{VERSION}} {u} /src/{d}")
    b.append("WORKDIR /src")
    if r.get("env"):
        for k, v in r["env"].items():
            b.append(f'ENV {k}="{v}"')
    if r.get("pre"):
        b.append("RUN " + " && ".join(r["pre"]))
    main = r.get("build") or [
        f'go build -trimpath -ldflags="{ldflags}" -o /tmp/x64_{n} {p}'
        for n, p in r["bins"]
    ]
    b.append(run_block(main))
    # cross-build for ARMv7 (pure Go -> free; cgo -> needs the C cross toolchain)
    if r.get("arm", True):
        if cgo:
            b.append("# --- ARMv7 cgo cross (musl.cc toolchain as C compiler) ---")
            b.append(f"ADD {ARM_TC_URL} /tmp/armtc.tgz")
            b.append("RUN tar -C /opt -zxf /tmp/armtc.tgz && rm /tmp/armtc.tgz")
            b.append("ENV PATH=/opt/arm-linux-musleabihf-cross/bin:$PATH")
            # a cgo tool usually needs its C dependency cross-built first
            if r.get("arm_pre"):
                b.append(run_block(r["arm_pre"]))
            armenv = " ".join(f'{k}="{v}"' for k, v in r.get("arm_env", {}).items())
            armenv = (armenv + " ") if armenv else ""
            armlines = [
                f'{armenv}CC=arm-linux-musleabihf-gcc GOARCH=arm GOARM=7 go build -trimpath -ldflags="{ldflags}" -o /tmp/arm_{n} {p}'
                for n, p in r["bins"]
            ]
        else:
            armlines = [
                f'GOARCH=arm GOARM=7 go build -trimpath -ldflags="{ldflags}" -o /tmp/arm_{n} {p}'
                for n, p in r["bins"]
            ]
        b.append(run_block(armlines))

    collect = [(f"/tmp/x64_{n}", f"/out/x64/{n}") for n, _ in r["bins"]]
    if r.get("arm", True):
        collect += [(f"/tmp/arm_{n}", f"/out/arm/{n}") for n, _ in r["bins"]]
    b.append(_collect_and_pack(collect, r))
    b.append(f"FROM {BASE_ALPINE}")
    b.append("COPY --from=build /out /out")
    return "\n".join(b) + "\n"


def rust_recipe(name, r):
    base = r.get("rust_image", RUST_IMAGE)
    b = [
        f"FROM {base} AS build",
        "ARG VERSION",
    ]
    if r.get("apt_pkgs"):
        b.append("RUN echo 'deb http://deb.debian.org/debian bookworm-backports main' "
                 ">> /etc/apt/sources.list.d/backports.list && apt-get update -qq "
                 "&& apt-get install -y --no-install-recommends "
                 f"{' '.join(r['apt_pkgs'])}")
    if r.get("pkgs"):
        b.append(f"RUN apk add --no-cache {' '.join(r['pkgs'])}")
    b += [
        # per-target flags so HOST proc-macros are built without crt-static
        'ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS="-C target-feature=+crt-static"',
        'ENV CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_RUSTFLAGS="-C target-feature=+crt-static"',
    ]
    # glibc base (apt): build scripts run on glibc (bindgen dlopens libclang),
    # final artifact still targets static musl via musl-gcc cross linker.
    if r.get("apt_pkgs"):
        b += [
            "RUN rustup target add x86_64-unknown-linux-musl",
            "ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc",
        ]
    else:
        b.append("RUN apk add --no-cache git ca-certificates upx musl-dev perl make")
    b += [fetch_lines(r), "WORKDIR /src"]
    if r.get("env"):
        for k, v in r["env"].items():
            b.append(f'ENV {k}="{v}"')
    if r.get("pre"):
        b.append("RUN " + " && ".join(r["pre"]))
    args = r.get("cargo_args", "")
    feats = ""
    if r.get("features"):
        feats = "--features " + ",".join(r["features"])
    bins = r["bins"]
    T64 = "x86_64-unknown-linux-musl"
    x64lines = [
        f'cargo build --release --target {T64} {args} {feats}'.replace("  ", " ").strip(),
    ]
    for n, p in bins:
        x64lines.append(f"cp target/{T64}/release/{p} /tmp/x64_{n}")
    b.append(run_block(x64lines))
    if r.get("arm", True):
        b.append("# --- ARMv7 cross (musl.cc toolchain as linker) ---")
        b.append(f"ADD {ARM_TC_URL} /tmp/armtc.tgz")
        b.append("RUN tar -C /opt -zxf /tmp/armtc.tgz && rm /tmp/armtc.tgz")
        b.append(
            "ENV PATH=/opt/arm-linux-musleabihf-cross/bin:$PATH \\\n"
            "    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER=arm-linux-musleabihf-gcc \\\n"
            "    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_AR=arm-linux-musleabihf-ar \\\n"
            "    CC_armv7_unknown_linux_musleabihf=arm-linux-musleabihf-gcc \\\n"
            "    AR_armv7_unknown_linux_musleabihf=arm-linux-musleabihf-ar"
        )
        b.append("RUN rustup target add armv7-unknown-linux-musleabihf")
        armlines = [f'cargo build --release --target armv7-unknown-linux-musleabihf {args} {feats}'.replace("  ", " ").strip()]
        for n, p in bins:
            armlines.append(
                f"cp target/armv7-unknown-linux-musleabihf/release/{p} /tmp/arm_{n}")
        b.append(run_block(armlines))

    collect = [(f"/tmp/x64_{n}", f"/out/x64/{n}") for n, _ in bins]
    if r.get("arm", True):
        collect += [(f"/tmp/arm_{n}", f"/out/arm/{n}") for n, _ in bins]
    b.append(_collect_and_pack(collect, r))
    b.append(f"FROM {BASE_ALPINE}")
    b.append("COPY --from=build /out /out")
    return "\n".join(b) + "\n"


def c_recipe(name, r):
    """C/C++ recipes: r['build'] must place final binaries at /tmp/out/<bin>
    (x64 phase) and /tmp/out-arm/<bin> (arm phase)."""
    is_cxx = r["lang"] == "cxx"
    base_pkgs = ["build-base", "git", "ca-certificates", "curl", "upx", "linux-headers", "xz", "bzip2"]
    if is_cxx:
        pass  # build-base includes g++
    b = [
        f"FROM {r.get('base_image', BASE_ALPINE)} AS build",
        "ARG VERSION",
        f"RUN apk add --no-cache {' '.join(base_pkgs + r.get('pkgs', []))}",
        fetch_lines(r),
        "WORKDIR /src",
    ]
    if r.get("env"):
        for k, v in r["env"].items():
            b.append(f'ENV {k}="{v}"')
    if r.get("pre"):
        b.append("RUN " + " && ".join(r["pre"]))
    b.append(run_block(["mkdir -p /tmp/out"] + r["build"]))

    if r.get("arm_build"):
        b.append("# --- ARMv7 cross (musl.cc toolchain) ---")
        b.append(f"ADD {ARM_TC_URL} /tmp/armtc.tgz")
        b.append("RUN tar -C /opt -zxf /tmp/armtc.tgz")
        b.append("ENV PATH=/opt/arm-linux-musleabihf-cross/bin:$PATH")
        b.append(run_block(["mkdir -p /tmp/out-arm"] + r["arm_build"]))

    collect = [(f"/tmp/out/{n}", f"/out/x64/{n}") for n, _ in r["bins"]]
    if r.get("arm_build"):
        collect += [(f"/tmp/out-arm/{n}", f"/out/arm/{n}") for n, _ in r["bins"]]
    # ARM-only tools ship no x64 binary but still need an /out tree
    if not collect and r.get("arm_only"):
        collect = [(f"/tmp/out-arm/{n}", f"/out/arm/{n}")
                   for n in r.get("arm_bins", [])]
    b.append(_collect_and_pack(collect, r))
    b.append(f"FROM {BASE_ALPINE}")
    b.append("COPY --from=build /out /out")
    return "\n".join(b) + "\n"


ARM_STRIP = "arm-linux-musleabihf-strip"


def _q(paths):
    return " ".join(f'"{p}"' for p in paths)


def _collect_and_pack(pairs, r):
    steps = [f"mkdir -p $(dirname {dst}) && cp {src} {dst}" for src, dst in pairs]

    # Strip only real ELF files. Some recipes produce shell wrappers / scripts
    # next to ELF binaries (e.g. wireshark's text2pcap), which `strip` would
    # reject; `file` tells them apart so we never abort on non-ELF, but still
    # strip every genuine binary. A build that produces no ELF at all is a
    # hard failure -- empty /out must not pass silently.
    if r["lang"] != "go":  # Go links with -s -w already
        for tag, stripbin in (("x64", "strip"), ("arm", ARM_STRIP)):
            bins = _q([dst for _, dst in pairs if f"/out/{tag}/" in dst])
            if bins:
                steps.append(f'for f in {bins}; do file "$f" | grep -q ELF && {stripbin} "$f" || true; done')

    # A build that shipped zero binaries is broken, not "successful but empty".
    allbins = [dst for _, dst in pairs]
    if allbins:
        steps.append(f'test -n "$(ls {_q(allbins)} 2>/dev/null | head -1)" || {{ echo "ERROR: no binaries produced"; exit 1; }}')

    # Everything here ships as a single static file. Several tools quietly did
    # not: dropbear's hardening adds -Wl,-pie, which beats -static; dsvpn and
    # icmptunnel link through CFLAGS; tor was never told to link statically.
    # A dynamic binary is useless on the targets this repo exists for, so the
    # build fails rather than shipping one. Checked before UPX, which hides it.
    if allbins:
        steps.append(
            f'for f in {_q(allbins)}; do file "$f" | grep -q ELF || continue; '
            f'file "$f" | grep -qE "statically linked|static-pie linked" || '
            f'{{ echo "ERROR: $f is dynamically linked"; file "$f"; exit 1; }}; done')

    if r.get("pack", True):
        # UPX is multi-arch; keep non-fatal only for genuinely unpackable
        # binaries (already-packed or format unsupported), but if nothing was
        # packed because nothing existed, the guard above already caught it.
        steps.append(f"( upx -q --best --lzma {_q(allbins)} || echo 'upx failed; shipping unpacked' )")

    return run_block(steps)


def main():
    names = sys.argv[1:]
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for name, r in RECIPES.items():
        if names and name not in names:
            continue
        d = os.path.join(root, "build", name)
        os.makedirs(d, exist_ok=True)
        fn = {"go": go_recipe, "rust": rust_recipe}.get(r["lang"], c_recipe)
        body = fn(name, r)
        head = HEADER.format(
            name=name,
            version_note="at a given ARG VERSION ",
            example_ver=(r.get("example_version") or "SET_ME"),
            arm_note=" and ARMv7" if r.get("arm", r["lang"] in ("go", "rust")) else "",
            dir=f"build/{name}",
        )
        with open(os.path.join(d, "Dockerfile"), "w") as f:
            f.write(head.lstrip() + "\n" + body)
        print(f"wrote build/{name}/Dockerfile")


if __name__ == "__main__":
    main()
